language: objective-c
osx_image: xcode7.1
cache:
  directories:
    - Lib/vendor/bundle
install:
  - (cd Lib && bundle install --path=vendor/bundle --binstubs=vendor/bin)
script:
  - (cd Lib && bundle exec rake build test:iphonesimulator test:appletvsimulator test:macosx coverage:coveralls)
branches:
  only:
    - master
env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
