language: objective-c
osx_image: xcode9
cache:
  directories:
  - Lib/vendor
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
install:
- "(cd Lib && bundle install --path=vendor/bundle --binstubs=vendor/bin)"
before_script:
- ./Lib/Scripts/decode_cert.sh || true
- ./Lib/Scripts/add_key.sh || true
script:
- "(cd Lib && bundle exec rake $ACTION)"
env:
  matrix:
  - ACTION=build
  - ACTION='build:carthage'
  - ACTION='test:iphonesimulator'
  - ACTION='test:appletvsimulator'
  - ACTION='test:macosx'
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - secure: KL59HA2XSRa215qVXXnFpx48Tb/k+vNfFAbzyc+0M4mXl1VhSJv3bkTslqDrX822t3iFDFYhXbJ6aUo7szSdcbnCXU7VIhNPRK5QM00eS1AI4V0UwDQZ06g2f4Dmt+cQxACg+0CB0OaPnUCA4rkQQKeBMAWa67Tp2hNgQHwsnio=
  - secure: B8zXiyX1zEq6uWaCxap5iW1joQBoOjNjSUlcs1t+QKdaFCFtjOI8C1JCClzk7rTnGNDDrhahFlE8yskSNKoBsaW2UJ8TzPIkD4F2pkxTHkaFQl/GBsdbHdOUFL4h0/zGQ6wY1Qhw7C+8+3U+1c9QbnNw6jOQwXTF6gs/XTNzG9Y=
branches:
  only:
  - master
